<?php namespace Pepijnolivier\HitBtc\Exception;

use Exception;

class RejectException extends HitbtcException
{
    /** @var array */
    protected $report;

    public function __construct($message = "", $report, $code = 0, Exception $previous = null)
    {
        $this->report = (array) $report;
        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getReport()
    {
        return $this->report;
    }

}
